### ISSUE TITLE
requirement missing

### ISSUE THREAD

**Issue by HaanJde** [netbox-community/reports#10]
Thanks for the fine work.

I had to do a "pip install dnspython" though, to get it going.

**Comment by mmahacek** [comment]
Yeah, there is a note at the top of the report file indicating that module is required.

**Comment by lampwins** [comment]
It is not the intent for this repo to be used in its entirety. It is just a repo of example reports. For that reason, we are not going to maintain a requires.txt in this repo. I will just ask that any reports that have 3rd party dependencies, to add a note in the report's docstring.
