### ISSUE TITLE
Wikimedia Netbox reports

### ISSUE THREAD

**Issue by XioNoX** [netbox-community/reports#12]
The reports we (at Wikimedia) made to keep our data consistent are available on https://gerrit.wikimedia.org/g/operations/software/netbox-reports, with a mirror on https://github.com/wikimedia/operations-software-netbox-reports
I don't think they would be of any value as-it, as they are tailored for our needs, but might be worth a link from your repo to ours. At least to get ideas and inspiration.
See our README for a quick description.
Fyi, all our Netbox related work is tracked on https://phabricator.wikimedia.org/tag/netbox/

**Comment by lampwins** [comment]
I would accept a PR to add an "other repo examples" section to the readme for these links. Otherwise, there is nothing actionable in this issue.
