### ISSUE TITLE
Unbundling of reports

### ISSUE THREAD

**Issue by candlerb** [netbox-community/reports#16]
In this repository, various reports from different people have been merged into the same source file - e.g. the single file [reports/ipam-reports/ip-reports.py](https://github.com/netbox-community/reports/blob/master/reports/ipam-reports/ip-reports.py) contains various IPAddress-related reports from different people.

I don't think this is a good idea. Reasons:

1. As an end user: if I want to install report A without report B (because report B isn't useful in my environment), I don't want to have to extract report A from the source code.
2. There are reports with overlapping functionality: e.g. in ip-reports, "test_primary_ip4" and "test_device_primary_ips". Again, as an end-user, I'm only going to want to install one or the other.
3. The top of the source file imports all the dependencies for all the reports, and once these are merged, it becomes unclear which reports have which dependencies.
4. It is difficult to track the author/contributor history of a particular report.

What I propose is that if an author submits a file, or a gist is copied in, then it should remain as-is - complete with its header of imports (and copyright/licence if present).  It should only be necessary to rename the file or classes if they clash with an existing report.

I don't mind if the top-level folders ("ipam-reports" and "dcim-reports") are kept. It's not always going to be clear which category a particular report ends up in, but it doesn't really matter if it's miscategorised.

**Comment by mmahacek** [comment]
That's a good idea, and I should have done that with my first batch.

**Comment by candlerb** [comment]
Also: there are likely to be more contrib things coming along (webhooks, custom scripts, ...)

Do you want separate repos for each of those, or a single contrib repo with top-level folders `reports/`, `webhooks/`, `scripts/`?

**Comment by mmahacek** [comment]
Personally I think one repo would be the easiest for users, not having to jump between different ones, but I'll leave that up to those in charge.

**Comment by lampwins** [comment]
It looks like this issue is resolved?

**Comment by mmahacek** [comment]
I think I unbundled all my reports.  There are a couple files that do have multiple reports in one file, but they are closely related to each other.  I have no objections to closing this.

**Comment by mmahacek** [comment]
@candlerb I had a couple that were similar but gave slightly different results, and left them in as separate files that users could use as samples depending on what they want.
