### ISSUE TITLE
Update Reports to work with v2.7.*

### ISSUE THREAD

**Issue by joshcorr** [netbox-community/reports#25]
Several of the reports seem to be broken on v2.7.* as a result of the change to some of the constants in python.

Here is an example Server Error

```
The complete exception is provided below:
<class 'NameError'>
name 'IPADDRESS_ROLE_LOOPBACK' is not defined
```

**Comment by mmahacek** [comment]
This should be addressed in https://github.com/netbox-community/reports/pull/20
