### ISSUE TITLE
ImportError in multi_connect.py

### ISSUE THREAD

**Issue by FlorianHeigl** [netbox-community/reports#60]
put the script in ./scripts of netbox-docker.

When accesing the "scripts" main menu item, netbox throws a server error (below).
I've seen that generally people use 'LinkStatusChoices', maybe it is deprecated, but i'm not really sure what's happening.

```
<class 'ImportError'>

cannot import name 'LinkStatusChoices' from 'dcim.choices' (/opt/netbox/netbox/dcim/choices.py)

Python version: 3.9.5
NetBox version: 3.0.6
```

**Comment by ryanmerolle** [comment]
Per the error, I pulled up [3.0.6 version of the dcim.choices](https://github.com/netbox-community/netbox/blob/v3.0.6/netbox/dcim/choices.py)

It looks like the script was created for 3.1+ as the name is found in [3.1.0 version of the dcim.choices](https://github.com/netbox-community/netbox/blob/5a59f2352c39e7040dd4537e5225d609cb14ffc1/netbox/dcim/choices.py#L1140)
